name: flutter_tcc_base_source
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.0.1
  cached_network_image: ^3.2.1
  json_serializable: ^6.2.0
  http: ^0.13.4
  get_it: ^7.2.0
  pretty_dio_logger: ^1.1.1
  dio: ^4.0.6
  intl: ^0.17.0
  fluttertoast: ^8.0.9
  equatable: ^2.0.3
  flutter_secure_storage: ^5.0.2
  retrofit: ^3.0.1+1
  logger: ^1.1.0
  flutter_svg: ^1.1.1+1
  firebase_core: ^1.19.1
  firebase_crashlytics: ^2.8.4
  firebase_analytics: ^9.1.12
  firebase_messaging: ^11.4.4
  flutter_focus_watcher: ^2.0.0
  package_info_plus: ^1.4.2
  introduction_screen: ^3.0.2
  google_sign_in: ^5.3.3
  flutter_login_facebook: ^1.5.0+1
  sign_in_with_apple: ^4.0.0
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/font/
    - locales/
  fonts:
    - family: HelveticaNowDisplay
      fonts:
        - asset: assets/font/HelveticaNowDisplay-Medium.otf
        - asset: assets/font/HelveticaNowDisplay-Bold.otf
          weight: 700
    - family: Metropolis
      fonts:
        - asset: assets/font/Metropolis-Regular.otf
        - asset: assets/font/Metropolis-Medium.otf
        - asset: assets/font/Metropolis-Bold.otf
          weight: 700
